function handle_company(what){
      if(what.value=="default"){
       document.getElementById('skye').style.display='none';
       document.getElementById('skye-button').style.display='none';
       document.getElementById('meras').style.display='none';
       document.getElementById('meras-button').style.display='none';
      }
     if(what.value=="skye"){
       document.getElementById('skye').style.display='block';
       document.getElementById('skye-button').style.display='block';
       document.getElementById('meras').style.display='none';
       document.getElementById('meras-button').style.display='none';
       document.getElementById('default').style.display='none';
       document.getElementById('default-button').style.display='none';
     }
     if(what.value=="meras"){
       document.getElementById('meras').style.display='block';
       document.getElementById('meras-button').style.display='block';
       document.getElementById('skye').style.display='none';
       document.getElementById('skye-button').style.display='none';           
       document.getElementById('default').style.display='none';
       document.getElementById('default-button').style.display='none';
     }
  }